
project_id = "bjkqxmvjuewshomihjqm"

[functions.telemetry-auth]
verify_jwt = false

[functions.telemetry-positions]
verify_jwt = false

[functions.user-management]
verify_jwt = true

[functions.vehicle-management]
verify_jwt = true

[functions.settings-management]
verify_jwt = true

[functions.passwordless-gp51-import]
verify_jwt = true

[functions.set-initial-password]
verify_jwt = false

[functions.gp51-data-preview]
verify_jwt = true

[functions.gp51-user-management]
verify_jwt = true

[functions.gp51-device-management]
verify_jwt = true

[functions.gp51-service-management]
verify_jwt = true
