
project_id = "bjkqxmvjuewshomihjqm"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54326
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://a5c4a0e1-3e52-4c78-95cf-31ee0b983a1d.lovableproject.com"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.gp51-service-management]
verify_jwt = false

[functions.gp51-scheduled-sync]
verify_jwt = false

[functions.enhanced-bulk-import]
verify_jwt = false

[functions.bulk-gp51-extraction]
verify_jwt = false

[functions.fetchLiveGp51Data]
verify_jwt = false

[functions.settings-management]
verify_jwt = false

[functions.telemetry-auth]
verify_jwt = false

[functions.telemetry-positions]
verify_jwt = false

[functions.syncGp51Vehicles]
verify_jwt = false

[functions.user-management]
verify_jwt = false

[functions.vehicle-sync-cron]
verify_jwt = false

[functions.gp51-live-import]
verify_jwt = false

[functions.enhanced-csv-import]
verify_jwt = false

[functions.full-system-import]
verify_jwt = false

[functions.gp51-secure-auth]
verify_jwt = false
