
project_id = "bjkqxmvjuewshomihjqm"

[functions.telemetry-auth]
verify_jwt = false

[functions.telemetry-positions]
verify_jwt = false

[functions.user-management]
verify_jwt = false

[functions.vehicle-management]
verify_jwt = false

[functions.settings-management]
verify_jwt = false
