import React from "react";
import {
  LayoutDashboard,
  Settings,
  User,
  Users,
  Building2,
  Car,
  Activity,
  Package2Icon,
  ShoppingCart,
  Percent,
  Mailbox,
  FileJson2,
  LucideIcon,
  BarChart4,
  Coins,
  MessageSquare,
  HelpCircle,
  FileText,
  LogOut,
  Plus,
  Edit,
  Trash2,
  Eye,
  EyeOff,
  CopyCheck,
  CopyX,
  Copy,
  ClipboardList,
  ClipboardCheck,
  ClipboardX,
  ClipboardCopy,
  ClipboardPaste,
  ClipboardType,
  ClipboardEdit,
  ClipboardSearch,
  ClipboardDown,
  ClipboardUp,
  ClipboardAlert,
  ClipboardUser,
  ClipboardSignature,
  ClipboardHeart,
  ClipboardSmile,
  ClipboardFrown,
  ClipboardInfo,
  ClipboardQuestion,
  ClipboardHelp,
  ClipboardCode,
  ClipboardData,
  ClipboardFile,
  ClipboardImage,
  ClipboardVideo,
  ClipboardAudio,
  ClipboardDocument,
  ClipboardText,
  ClipboardPdf,
  ClipboardZip,
  ClipboardXml,
  ClipboardSvg,
  ClipboardJsx,
  ClipboardTsx,
  ClipboardJson,
  ClipboardYaml,
  ClipboardMd,
  ClipboardHtml,
  ClipboardCss,
  ClipboardSql,
  ClipboardPy,
  ClipboardJava,
  ClipboardC,
  ClipboardCpp,
  ClipboardCs,
  ClipboardGo,
  ClipboardRs,
  ClipboardSwift,
  ClipboardKotlin,
  ClipboardPhp,
  ClipboardRb,
  ClipboardLua,
  ClipboardDart,
  ClipboardHaskell,
  ClipboardErlang,
  ClipboardElixir,
  ClipboardClojure,
  ClipboardScala,
  ClipboardGroovy,
  ClipboardObjectiveC,
  ClipboardSwiftUi,
  ClipboardFlutter,
  ClipboardReact,
  ClipboardVue,
  ClipboardAngular,
  ClipboardSvelte,
  ClipboardEmber,
  ClipboardBackbone,
  ClipboardJquery,
  ClipboardBootstrap,
  ClipboardMaterialUi,
  ClipboardTailwindCss,
  ClipboardAntDesign,
  ClipboardSemanticUi,
  ClipboardBulma,
  ClipboardFoundation,
  ClipboardPureCss,
  ClipboardSkeleton,
  ClipboardMilligram,
  ClipboardPicnicCss,
  ClipboardSpectreCss,
  ClipboardTachyons,
  ClipboardBasscss,
  ClipboardPrimerCss,
  ClipboardMincss,
  ClipboardHolidayCss,
  ClipboardAwsmCss,
  ClipboardBojwourCss,
  ClipboardChotaCss,
  ClipboardCirrusCss,
  ClipboardConciseCss,
  ClipboardCutestrap,
  ClipboardFurtiveCss,
  ClipboardInkCss,
  ClipboardKube,
  ClipboardLit,
  ClipboardMobiCss,
  ClipboardNesCss,
  ClipboardNewCss,
  ClipboardOocss,
  ClipboardPaperCss,
  ClipboardPcss,
  ClipboardRebootCss,
  ClipboardSakura,
  ClipboardSimpleCss,
  ClipboardSiimple,
  ClipboardSketcss,
  ClipboardSpark,
  ClipboardStylize,
  ClipboardTacit,
  ClipboardTufteCss,
  ClipboardUikit,
  ClipboardVanillaCss,
  ClipboardWaterCss,
  ClipboardWing,
  ClipboardZola,
  Clipboard,
  FileTextIcon,
  FileImageIcon,
  FileVideoIcon,
  FileAudioIcon,
  FileDocumentIcon,
  FilePdfIcon,
  FileZipIcon,
  FileXmlIcon,
  FileSvgIcon,
  FileJsxIcon,
  FileTsxIcon,
  FileJsonIcon,
  FileYamlIcon,
  FileMdIcon,
  FileHtmlIcon,
  FileCssIcon,
  FileSqlIcon,
  FilePyIcon,
  FileJavaIcon,
  FileCIcon,
  FileCppIcon,
  FileCsIcon,
  FileGoIcon,
  FileRsIcon,
  FileSwiftIcon,
  FileKotlinIcon,
  FilePhpIcon,
  FileRbIcon,
  FileLuaIcon,
  FileDartIcon,
  FileHaskellIcon,
  FileErlangIcon,
  FileElixirIcon,
  FileClojureIcon,
  FileScalaIcon,
  FileGroovyIcon,
  FileObjectiveCIcon,
  FileSwiftUiIcon,
  FileFlutterIcon,
  FileReactIcon,
  FileVueIcon,
  FileAngularIcon,
  FileSvelteIcon,
  FileEmberIcon,
  FileBackboneIcon,
  FileJqueryIcon,
  FileBootstrapIcon,
  FileMaterialUiIcon,
  FileTailwindCssIcon,
  FileAntDesignIcon,
  FileSemanticUiIcon,
  FileBulmaIcon,
  FileFoundationIcon,
  FilePureCssIcon,
  FileSkeletonIcon,
  FileMilligramIcon,
  FilePicnicCssIcon,
  FileSpectreCssIcon,
  FileTachyonsIcon,
  FileBasscssIcon,
  FilePrimerCssIcon,
  FileMincssIcon,
  FileHolidayCssIcon,
  FileAwsmCssIcon,
  FileBojwourCssIcon,
  FileChotaCssIcon,
  FileCirrusCssIcon,
  FileConciseCssIcon,
  FileCutestrapIcon,
  FileFurtiveCssIcon,
  FileInkCssIcon,
  FileKubeIcon,
  FileLitIcon,
  FileMobiCssIcon,
  FileNesCssIcon,
  FileNewCssIcon,
  FileOocssIcon,
  FilePaperCssIcon,
  FilePcssIcon,
  FileRebootCssIcon,
  FileSakuraIcon,
  FileSimpleCssIcon,
  FileSiimpleIcon,
  FileSketcssIcon,
  FileSparkIcon,
  FileStylizeIcon,
  FileTacitIcon,
  FileTufteCssIcon,
  FileUikitIcon,
  FileVanillaCssIcon,
  FileWaterCssIcon,
  FileWingIcon,
  FileZolaIcon,
  FileIcon,
  File,
  FileEdit,
  FilePlus,
  FileSearch,
  FileDown,
  FileUp,
  FileAlert,
  FileUser,
  FileSignature,
  FileHeart,
  FileSmile,
  FileFrown,
  FileInfo,
  FileQuestion,
  FileHelp,
  FileCode,
  FileData,
  FileImage,
  FileVideo,
  FileAudio,
  FileDocument,
  FileTextFile,
  FilePdf,
  FileZip,
  FileXml,
  FileSvg,
  FileJsx,
  FileTsx,
  FileJson,
  FileYaml,
  FileMd,
  FileHtml,
  FileCss,
  FileSql,
  FilePy,
  FileJava,
  FileC,
  FileCpp,
  FileCs,
  FileGo,
  FileRs,
  FileSwift,
  FileKotlin,
  FilePhp,
  FileRb,
  FileLua,
  FileDart,
  FileHaskell,
  FileErlang,
  FileElixir,
  FileClojure,
  FileScala,
  FileGroovy,
  FileObjectiveC,
  FileSwiftUi,
  FileFlutter,
  FileReact,
  FileVue,
  FileAngular,
  FileSvelte,
  FileEmber,
  FileBackbone,
  FileJquery,
  FileBootstrap,
  FileMaterialUi,
  FileTailwindCss,
  FileAntDesign,
  FileSemanticUi,
  FileBulma,
  FileFoundation,
  FilePureCss,
  FileSkeleton,
  FileMilligram,
  FilePicnicCss,
  FileSpectreCss,
  FileTachyons,
  FileBasscss,
  FilePrimerCss,
  FileMincss,
  FileHolidayCss,
  FileAwsmCss,
  FileBojwourCss,
  FileChotaCss,
  FileCirrusCss,
  FileConciseCss,
  FileCutestrap,
  FileFurtiveCss,
  FileInkCss,
  FileKube,
  FileLit,
  FileMobiCss,
  FileNesCss,
  FileNewCss,
  FileOocss,
  FilePaperCss,
  FilePcss,
  FileRebootCss,
  FileSakura,
  FileSimpleCss,
  FileSiimple,
  FileSketcss,
  FileSpark,
  FileStylize,
  FileTacit,
  FileTufteCss,
  FileUikit,
  FileVanillaCss,
  FileWaterCss,
  FileWing,
  FileZola,
  FileCode2,
  FileEdit2,
  FilePlus2,
  FileSearch2,
  FileDown2,
  FileUp2,
  FileAlert2,
  FileUser2,
  FileSignature2,
  FileHeart2,
  FileSmile2,
  FileFrown2,
  FileInfo2,
  FileQuestion2,
  FileHelp2,
  FileData2,
  FileImage2,
  FileVideo2,
  FileAudio2,
  FileDocument2,
  FileTextFile2,
  FilePdf2,
  FileZip2,
  FileXml2,
  FileSvg2,
  FileJsx2,
  FileTsx2,
  FileJson2,
  FileYaml2,
  FileMd2,
  FileHtml2,
  FileCss2,
  FileSql2,
  FilePy2,
  FileJava2,
  FileC2,
  FileCpp2,
  FileCs2,
  FileGo2,
  FileRs2,
  FileSwift2,
  FileKotlin2,
  FilePhp2,
  FileRb2,
  FileLua2,
  FileDart2,
  FileHaskell2,
  FileErlang2,
  FileElixir2,
  FileClojure2,
  FileScala2,
  FileGroovy2,
  FileObjectiveC2,
  FileSwiftUi2,
  FileFlutter2,
  FileReact2,
  FileVue2,
  FileAngular2,
  FileSvelte2,
  FileEmber2,
  FileBackbone2,
  FileJquery2,
  FileBootstrap2,
  FileMaterialUi2,
  FileTailwindCss2,
  FileAntDesign2,
  FileSemanticUi2,
  FileBulma2,
  FileFoundation2,
  FilePureCss2,
  FileSkeleton2,
  FileMilligram2,
  FilePicnicCss2,
  FileSpectreCss2,
  FileTachyons2,
  FileBasscss2,
  FilePrimerCss2,
  FileMincss2,
  FileHolidayCss2,
  FileAwsmCss2,
  FileBojwourCss2,
  FileChotaCss2,
  FileCirrusCss2,
  FileConciseCss2,
  FileCutestrap2,
  FileFurtiveCss2,
  FileInkCss2,
  FileKube2,
  FileLit2,
  FileMobiCss2,
  FileNesCss2,
  FileNewCss2,
  FileOocss2,
  FilePaperCss2,
  FilePcss2,
  FileRebootCss2,
  FileSakura2,
  FileSimpleCss2,
  FileSiimple2,
  FileSketcss2,
  FileSpark2,
  FileStylize2,
  FileTacit2,
  FileTufteCss2,
  FileUikit2,
  FileVanillaCss2,
  FileWaterCss2,
  FileWing2,
  FileZola2,
  FileCode3,
  FileEdit3,
  FilePlus3,
  FileSearch3,
  FileDown3,
  FileUp3,
  FileAlert3,
  FileUser3,
  FileSignature3,
  FileHeart3,
  FileSmile3,
  FileFrown3,
  FileInfo3,
  FileQuestion3,
  FileHelp3,
  FileData3,
  FileImage3,
  FileVideo3,
  FileAudio3,
  FileDocument3,
  FileTextFile3,
  FilePdf3,
  FileZip3,
  FileXml3,
  FileSvg3,
  FileJsx3,
  FileTsx3,
  FileJson3,
  FileYaml3,
  FileMd3,
  FileHtml3,
  FileCss3,
  FileSql3,
  FilePy3,
  FileJava3,
  FileC3,
  FileCpp3,
  FileCs3,
  FileGo3,
  FileRs3,
  FileSwift3,
  FileKotlin3,
  FilePhp3,
  FileRb3,
  FileLua3,
  FileDart3,
  FileHaskell3,
  FileErlang3,
  FileElixir3,
  FileClojure3,
  FileScala3,
  FileGroovy3,
  FileObjectiveC3,
  FileSwiftUi3,
  FileFlutter3,
  FileReact3,
  FileVue3,
  FileAngular3,
  FileSvelte3,
  FileEmber3,
  FileBackbone3,
  FileJquery3,
  FileBootstrap3,
  FileMaterialUi3,
  FileTailwindCss3,
  FileAntDesign3,
  FileSemanticUi3,
  FileBulma3,
  FileFoundation3,
  FilePureCss3,
  FileSkeleton3,
  FileMilligram3,
  FilePicnicCss3,
  FileSpectreCss3,
  FileTachyons3,
  FileBasscss3,
  FilePrimerCss3,
  FileMincss3,
  FileHolidayCss3,
  FileAwsmCss3,
  FileBojwourCss3,
  FileChotaCss3,
  FileCirrusCss3,
  FileConciseCss3,
  FileCutestrap3,
  FileFurtiveCss3,
  FileInkCss3,
  FileKube3,
  FileLit3,
  FileMobiCss3,
  FileNesCss3,
  FileNewCss3,
  FileOocss3,
  FilePaperCss3,
  FilePcss3,
  FileRebootCss3,
  FileSakura3,
  FileSimpleCss3,
  FileSiimple3,
  FileSketcss3,
  FileSpark3,
  FileStylize3,
  FileTacit3,
  FileTufteCss3,
  FileUikit3,
  FileVanillaCss3,
  FileWaterCss3,
  FileWing3,
  FileZola3,
  FileCode4,
  FileEdit4,
  FilePlus4,
  FileSearch4,
  FileDown4,
  FileUp4,
  FileAlert4,
  FileUser4,
  FileSignature4,
  FileHeart4,
  FileSmile4,
  FileFrown4,
  FileInfo4,
  FileQuestion4,
  FileHelp4,
  FileData4,
  FileImage4,
  FileVideo4,
  FileAudio4,
  FileDocument4,
  FileTextFile4,
  FilePdf4,
  FileZip4,
  FileXml4,
  FileSvg4,
  FileJsx4,
  FileTsx4,
  FileJson4,
  FileYaml4,
  FileMd4,
  FileHtml4,
  FileCss4,
  FileSql4,
  FilePy4,
  FileJava4,
  FileC4,
  FileCpp4,
  FileCs4,
  FileGo4,
  FileRs4,
  FileSwift4,
  FileKotlin4,
  FilePhp4,
  FileRb4,
  FileLua4,
  FileDart4,
  FileHaskell4,
  FileErlang4,
  FileElixir4,
  FileClojure4,
  FileScala4,
  FileGroovy4,
  FileObjectiveC4,
  FileSwiftUi4,
  FileFlutter4,
  FileReact4,
  FileVue4,
  FileAngular4,
  FileSvelte4,
  FileEmber4,
  FileBackbone4,
  FileJquery4,
  FileBootstrap4,
  FileMaterialUi4,
  FileTailwindCss4,
  FileAntDesign4,
  FileSemanticUi4,
  FileBulma4,
  FileFoundation4,
  FilePureCss4,
  FileSkeleton4,
  FileMilligram4,
  FilePicnicCss4,
  FileSpectreCss4,
  FileTachyons4,
  FileBasscss4,
  FilePrimerCss4,
  FileMincss4,
  FileHolidayCss4,
  FileAwsmCss4,
  FileBojwourCss4,
  FileChotaCss4,
  FileCirrusCss4,
  FileConciseCss4,
  FileCutestrap4,
  FileFurtiveCss4,
  FileInkCss4,
  FileKube4,
  FileLit4,
  FileMobiCss4,
  FileNesCss4,
  FileNewCss4,
  FileOocss4,
  FilePaperCss4,
  FilePcss4,
  FileRebootCss4,
  FileSakura4,
  FileSimpleCss4,
  FileSiimple4,
  FileSketcss4,
  FileSpark4,
  FileStylize4,
  FileTacit4,
  FileTufteCss4,
  FileUikit4,
  FileVanillaCss4,
  FileWaterCss4,
  FileWing4,
  FileZola4,
} from "lucide-react";
import { NavLink } from "react-router-dom";
import { useAuth } from "@/hooks/useAuth";

interface SidebarItem {
  title: string;
  icon: LucideIcon;
  href: string;
  roles: string[];
  description: string;
}

const sidebarItems = [
  {
    title: "Dashboard",
    icon: LayoutDashboard,
    href: "/",
    roles: ["admin", "end_user", "sub_admin"],
    description: "Quick overview of key metrics and data"
  },
  {
    title: "Vehicles",
    icon: Car,
    href: "/vehicles",
    roles: ["admin", "end_user", "sub_admin"],
    description: "Manage and track your fleet vehicles"
  },
  {
    title: "Users",
    icon: Users,
    href: "/users",
    roles: ["admin", "sub_admin"],
    description: "Manage user accounts and permissions"
  },
  {
    title: "Workshops",
    icon: Building2,
    href: "/workshops",
    roles: ["admin", "sub_admin"],
    description: "Manage workshop locations and services"
  },
  {
    title: "Packages",
    icon: Package2Icon,
    href: "/packages",
    roles: ["admin", "sub_admin"],
    description: "Manage subscription packages and features"
  },
  {
    title: "Marketplace",
    icon: ShoppingCart,
    href: "/marketplace",
    roles: ["admin", "end_user", "sub_admin"],
    description: "Explore and purchase vehicle services"
  },
  {
    title: "Promotions",
    icon: Percent,
    href: "/promotions",
    roles: ["admin", "sub_admin"],
    description: "Create and manage promotional offers"
  },
  {
    title: "Email",
    icon: Mailbox,
    href: "/email",
    roles: ["admin"],
    description: "Manage email templates and settings"
  },
  {
    title: "Telemetry",
    icon: FileJson2,
    href: "/telemetry",
    roles: ["admin"],
    description: "View and analyze telemetry data"
  },
  {
    title: "Analytics",
    icon: BarChart4,
    href: "/analytics",
    roles: ["admin"],
    description: "Analyze system performance and usage"
  },
  {
    title: "Billing",
    icon: Coins,
    href: "/billing",
    roles: ["admin", "end_user", "sub_admin"],
    description: "Manage billing information and subscriptions"
  },
  {
    title: "Support",
    icon: MessageSquare,
    href: "/support",
    roles: ["admin", "end_user", "sub_admin"],
    description: "Access support resources and contact support"
  },
  {
    title: "Help",
    icon: HelpCircle,
    href: "/help",
    roles: ["admin", "end_user", "sub_admin"],
    description: "Access help documentation and tutorials"
  },
  {
    title: "System Monitoring",
    icon: Activity,
    href: "/monitoring",
    roles: ["admin"],
    description: "System health and monitoring dashboard"
  },
];

const Sidebar: React.FC = () => {
  const { user, signOut, hasRole } = useAuth();

  return (
    <div className="w-64 bg-gray-100 h-screen fixed top-0 left-0 overflow-y-auto border-r border-gray-200">
      <div className="p-4">
        <h1 className="text-2xl font-bold text-gray-800">FleetIQ</h1>
        <p className="text-sm text-gray-500 mt-1">
          Welcome, {user?.email || "Guest"}!
        </p>
      </div>

      <nav className="mt-6">
        {sidebarItems.map((item) =>
          item.roles.some((role) => hasRole(role)) ? (
            <NavLink
              key={item.title}
              to={item.href}
              className={({ isActive }) =>
                `flex items-center p-3 rounded-md text-gray-700 hover:bg-gray-200 transition-colors duration-200 ${
                  isActive ? "bg-gray-200 font-semibold" : ""
                }`
              }
            >
              <item.icon className="w-5 h-5 mr-3" />
              {item.title}
            </NavLink>
          ) : null
        )}
      </nav>

      <div className="p-4 mt-auto">
        <button
          onClick={signOut}
          className="w-full py-2 px-4 bg-red-500 text-white rounded-md hover:bg-red-600 transition-colors duration-200"
        >
          <LogOut className="w-4 h-4 mr-2 inline-block" />
          Sign Out
        </button>
      </div>
    </div>
  );
};

export default Sidebar;
