import { GP51Device, GP51Position, GP51Group, safeNumber, safeString, safeDateToString } from '@/types/gp51-unified';

export class GP51TypeMapper {
  static mapDevice(apiDevice: any): GP51Device {
    return {
      deviceid: safeString(apiDevice.deviceid),
      devicename: safeString(apiDevice.devicename),
      devicetype: safeNumber(apiDevice.devicetype, 0),
      simnum: apiDevice.simnum,
      overduetime: safeNumber(apiDevice.overduetime),
      expirenotifytime: safeNumber(apiDevice.expirenotifytime),
      remark: apiDevice.remark,
      creater: apiDevice.creater,
      videochannelcount: safeNumber(apiDevice.videochannelcount),
      lastactivetime: safeNumber(apiDevice.lastactivetime),
      isfree: safeNumber(apiDevice.isfree),
      allowedit: safeNumber(apiDevice.allowedit),
      icon: safeNumber(apiDevice.icon),
      stared: safeNumber(apiDevice.stared),
      loginame: apiDevice.loginame,
      groupid: safeNumber(apiDevice.groupid),
      groupname: apiDevice.groupname
    };
  }

  static mapPosition(apiPosition: any): GP51Position {
    return {
      deviceid: safeString(apiPosition.deviceid),
      devicetime: safeNumber(apiPosition.devicetime),
      arrivedtime: safeNumber(apiPosition.arrivedtime),
      updatetime: safeNumber(apiPosition.updatetime),
      validpoistiontime: safeNumber(apiPosition.validpoistiontime),
      callat: safeNumber(apiPosition.callat, 0),
      callon: safeNumber(apiPosition.callon, 0),
      altitude: safeNumber(apiPosition.altitude),
      radius: safeNumber(apiPosition.radius),
      speed: safeNumber(apiPosition.speed),
      course: safeNumber(apiPosition.course),
      totaldistance: safeNumber(apiPosition.totaldistance),
      totaloil: safeNumber(apiPosition.totaloil),
      totalnotrunningad: safeNumber(apiPosition.totalnotrunningad),
      masteroil: safeNumber(apiPosition.masteroil),
      auxoil: safeNumber(apiPosition.auxoil),
      thirdoil: safeNumber(apiPosition.thirdoil),
      fourthoil: safeNumber(apiPosition.fourthoil),
      srcad0: safeNumber(apiPosition.srcad0),
      srcad1: safeNumber(apiPosition.srcad1),
      srcad2: safeNumber(apiPosition.srcad2),
      srcad3: safeNumber(apiPosition.srcad3),
      status: safeNumber(apiPosition.status),
      strstatus: apiPosition.strstatus,
      strstatusen: apiPosition.strstatusen,
      alarm: safeNumber(apiPosition.alarm),
      stralarm: apiPosition.stralarm,
      stralarmsen: apiPosition.stralarmsen,
      videoalarm: safeNumber(apiPosition.videoalarm),
      strvideoalarm: apiPosition.strvideoalarm,
      strvideoalarmen: apiPosition.strvideoalarmen,
      videosignalloststatus: safeNumber(apiPosition.videosignalloststatus),
      videosignalcoverstatus: safeNumber(apiPosition.videosignalcoverstatus),
      videobehavior: safeNumber(apiPosition.videobehavior),
      videofatiguedegree: safeNumber(apiPosition.videofatiguedegree),
      gotsrc: apiPosition.gotsrc,
      gpsvalidnum: safeNumber(apiPosition.gpsvalidnum),
      exvoltage: safeNumber(apiPosition.exvoltage),
      voltagev: safeNumber(apiPosition.voltagev),
      voltagepercent: safeNumber(apiPosition.voltagepercent),
      moving: safeNumber(apiPosition.moving),
      parklat: safeNumber(apiPosition.parklat),
      parklon: safeNumber(apiPosition.parklon),
      parktime: safeNumber(apiPosition.parktime),
      parkduration: safeNumber(apiPosition.parkduration),
      temp1: safeNumber(apiPosition.temp1),
      temp2: safeNumber(apiPosition.temp2),
      temp3: safeNumber(apiPosition.temp3),
      temp4: safeNumber(apiPosition.temp4),
      humi1: safeNumber(apiPosition.humi1),
      humi2: safeNumber(apiPosition.humi2),
      iostatus: safeNumber(apiPosition.iostatus),
      currentoverspeedstate: safeNumber(apiPosition.currentoverspeedstate),
      rotatestatus: safeNumber(apiPosition.rotatestatus),
      loadstatus: safeNumber(apiPosition.loadstatus),
      weight: safeNumber(apiPosition.weight),
      srcweightad0: safeNumber(apiPosition.srcweightad0),
      reportmode: safeNumber(apiPosition.reportmode),
      servertime: safeDateToString(apiPosition.servertime),
      battery: safeNumber(apiPosition.battery || apiPosition.voltagepercent, 0),
      signal: safeNumber(apiPosition.signal || apiPosition.rxlevel, 0),
      satellites: safeNumber(apiPosition.satellites || apiPosition.gpsvalidnum, 0),
      alarmtype: safeNumber(apiPosition.alarmtype)
    };
  }

  static mapGroup(apiGroup: any): GP51Group {
    return {
      groupid: safeNumber(apiGroup.groupid, 0),
      groupname: safeString(apiGroup.groupname),
      remark: apiGroup.remark,
      devices: apiGroup.devices?.map((device: any) => this.mapDevice(device)) || [],
      parentgroupid: safeNumber(apiGroup.parentgroupid, 0),
      id: safeNumber(apiGroup.id || apiGroup.groupid),
      group_name: apiGroup.group_name || apiGroup.groupname,
      group_id: safeNumber(apiGroup.group_id || apiGroup.groupid),
      device_count: safeNumber(apiGroup.device_count || apiGroup.devices?.length, 0),
      devicecount: safeNumber(apiGroup.devicecount || apiGroup.devices?.length, 0),
      last_sync_at: safeDateToString(apiGroup.last_sync_at),
      level: safeNumber(apiGroup.level)
    };
  }
}
