
export type ReferralAgentStatus = 'pending_approval' | 'active' | 'suspended' | 'rejected';
export type CommissionSourceType = 'subscription_upgrade' | 'marketplace_fee';
export type CommissionStatus = 'pending_payout' | 'paid' | 'cancelled';
export type PayoutRequestStatus = 'pending' | 'approved' | 'processing' | 'paid' | 'rejected';

export interface ReferralSettings {
  id: 1;
  agent_commission_rate_subscription: number;
  agent_commission_rate_marketplace: number;
  commission_duration_days: number;
  trial_package_id?: string | null;
  trial_duration_days: number;
  allow_subscription_commissions: boolean;
  allow_marketplace_commissions: boolean;
  agent_annual_fee: number;
  updated_at: string;
}

export interface ReferralAgent {
  id: string;
  user_id: string;
  status: ReferralAgentStatus;
  bank_account_details?: any | null;
  approved_by?: string | null;
  approved_at?: string | null;
  subscription_expires_at?: string | null;
  created_at: string;
  updated_at: string;
}

export interface ReferralCode {
  id: string;
  agent_id: string;
  code: string;
  usage_count: number;
  is_active: boolean;
  created_at: string;
}

export interface ReferredUser {
  id: string;
  referred_user_id: string;
  referring_agent_id: string;
  referral_code_id?: string | null;
  signed_up_at: string;
  commission_earnings_end_date: string;
}

export interface ReferralCommission {
  id: string;
  agent_id: string;
  referred_user_id: string;
  source_type: CommissionSourceType;
  source_id: string;
  source_amount: number;
  commission_rate: number;
  readonly commission_amount: number; // Generated by DB
  status: CommissionStatus;
  created_at: string;
  paid_at?: string | null;
}

export interface ReferralAgentSubscription {
  id: string;
  agent_id: string;
  start_date: string;
  end_date: string;
  amount_paid: number;
  payment_id?: string | null;
  created_at: string;
}

export interface ReferralAgentWithUserDetails extends ReferralAgent {
  name: string;
  email: string;
}

export interface AgentDashboardAnalytics {
  totalEarned: number;
  pendingCommissions: number;
  processingPayouts: number;
  earnedThisMonth: number;
  earnedLastMonth: number;
  totalCodes: number;
  totalUsageCount: number;
  totalReferredUsers: number;
  referredUsersThisMonth: number;
  referredUsersLastMonth: number;
  monthlyCommissions: { name: string; total: number }[];
}

export interface ReferredUserWithDetails extends ReferredUser {
  referred_user_name: string;
  referred_user_email: string;
  referral_code: string;
}

export interface CommissionWithDetails extends ReferralCommission {
  referred_user_name: string;
}

export interface AgentPayoutRequest {
    id: string;
    agent_id: string;
    amount: number;
    status: PayoutRequestStatus;
    requested_at: string;
    processed_at?: string | null;
    transaction_ref?: string | null;
    admin_notes?: string | null;
}

export interface AgentPerformanceSnapshot {
  id: string;
  agent_id: string;
  snapshot_date: string;
  total_referrals: number;
  total_signups: number;
  total_conversions: number;
  total_commission_earned: number;
  created_at: string;
}

export interface TopAgent {
  agent_id: string;
  agent_name: string;
  agent_email: string;
  total_commission: number;
}

export interface SystemReferralAnalytics {
  total_referrals: number;
  total_signups: number;
  total_conversions: number;
  total_commission: number;
  top_agents: TopAgent[];
}
