
interface ProviderConfig {
  name: string;
  host: string;
  port: number;
  use_ssl: boolean;
  use_tls: boolean;
  description: string;
  pricing: string;
  setupSteps: string[];
  dnsRecords: {
    spf: string;
    dkim: string;
    dmarc: string;
  };
  advantages: string[];
}

export const providers: Record<string, ProviderConfig> = {
  resend: {
    name: 'Resend',
    host: 'smtp.resend.com',
    port: 587,
    use_ssl: false,
    use_tls: true,
    description: 'Modern email API designed for developers',
    pricing: '100 emails/day free, then $20/month for 50k emails',
    setupSteps: [
      'Sign up at resend.com',
      'Verify your email address',
      'Add and verify your domain',
      'Create an API key',
      'Configure DNS records'
    ],
    dnsRecords: {
      spf: 'v=spf1 include:_spf.resend.com ~all',
      dkim: 'Contact Resend support for DKIM configuration',
      dmarc: 'v=DMARC1; p=quarantine; rua=mailto:dmarc@yourdomain.com'
    },
    advantages: [
      'Developer-friendly API',
      'Built-in analytics',
      'High deliverability',
      'React email templates'
    ]
  },
  sendgrid: {
    name: 'SendGrid',
    host: 'smtp.sendgrid.net',
    port: 587,
    use_ssl: false,
    use_tls: true,
    description: 'Enterprise-grade email delivery platform',
    pricing: '100 emails/day free, then $19.95/month for 50k emails',
    setupSteps: [
      'Create SendGrid account',
      'Complete account verification',
      'Set up domain authentication',
      'Create API key with full access',
      'Configure sender identity'
    ],
    dnsRecords: {
      spf: 'v=spf1 include:sendgrid.net ~all',
      dkim: 'Auto-generated by SendGrid during domain setup',
      dmarc: 'v=DMARC1; p=quarantine; rua=mailto:dmarc@yourdomain.com'
    },
    advantages: [
      'Robust analytics',
      'Template management',
      'A/B testing',
      'High volume support'
    ]
  },
  ses: {
    name: 'Amazon SES',
    host: 'email-smtp.us-east-1.amazonaws.com',
    port: 587,
    use_ssl: false,
    use_tls: true,
    description: 'AWS-powered email service with high reliability',
    pricing: '$0.10 per 1,000 emails (very cost-effective)',
    setupSteps: [
      'Create AWS account',
      'Access SES console',
      'Verify domain identity',
      'Create SMTP credentials',
      'Request production access'
    ],
    dnsRecords: {
      spf: 'v=spf1 include:amazonses.com ~all',
      dkim: 'Auto-generated during domain verification',
      dmarc: 'v=DMARC1; p=quarantine; rua=mailto:dmarc@yourdomain.com'
    },
    advantages: [
      'Extremely cost-effective',
      'AWS integration',
      'High scalability',
      'Detailed metrics'
    ]
  },
  mailgun: {
    name: 'Mailgun',
    host: 'smtp.mailgun.org',
    port: 587,
    use_ssl: false,
    use_tls: true,
    description: 'Email automation service for developers',
    pricing: '5,000 emails free for 3 months, then $15/month',
    setupSteps: [
      'Sign up at mailgun.com',
      'Add your domain',
      'Verify domain ownership',
      'Get SMTP credentials',
      'Configure webhooks (optional)'
    ],
    dnsRecords: {
      spf: 'v=spf1 include:mailgun.org ~all',
      dkim: 'Auto-generated during domain setup',
      dmarc: 'v=DMARC1; p=quarantine; rua=mailto:dmarc@yourdomain.com'
    },
    advantages: [
      'Powerful API',
      'Email validation',
      'Inbox placement optimization',
      'European data centers'
    ]
  }
};
